spring:
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

grpc:
  client:
    catalogue-service:
      address: 'static://localhost:9091'
      negotiation-type: plaintext
    orders-service:
      address: 'static://localhost:9092'
      negotiation-type: plaintext
    auth-service:
      address: 'static://localhost:9093'
      negotiation-type: plaintext
    payment-service:
      address: 'static://localhost:9094'
      negotiation-type: plaintext

logging:
  level:
    root: INFO
    com.quickcommerce: DEBUG
    graphql.execution: DEBUG
