spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/quickcommerce
    username: admin
    password: password

razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}

grpc:
  client:
    orders-service:
      address: 'static://orders-service:9092'
      negotiation-type: plaintext
    auth-service:
      address: 'static://auth-service:9093'
      negotiation-type: plaintext
